language: node_js
node_js:
  - 10
cache: yarn
before_install:
  - 'npm install msw'
before_script:
  - 'npm run build'

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
